apiVersion: v1
kind: Service
metadata:
 name: service
 labels:
  app: heart-disease-prediction
spec:
 type: NodePort
 selector:
  app: heart-disease-prediction
 ports:
 - port: 8501
   targetPort: 8501
   nodePort: 30001


